#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

COMMAND="${1:-up}"
DEMO_ENV_FILE="${DEMO_ENV_FILE:-.env.demo}"
API_BASE_URL="${API_BASE_URL:-http://localhost:8080}"
WEB_URL="${WEB_URL:-http://localhost:8088}"
RABBITMQ_URL="${RABBITMQ_URL:-http://localhost:15672}"
HEALTH_TIMEOUT_SECONDS="${HEALTH_TIMEOUT_SECONDS:-300}"
HEALTH_POLL_SECONDS="${HEALTH_POLL_SECONDS:-5}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-$(basename "$ROOT_DIR")}"
DEMO_CONTAINERS=(
  knowledgeops-agent
  knowledgeops-agent-web
  knowledgeops-agent-mysql
  knowledgeops-agent-redis
  knowledgeops-agent-rabbitmq
  knowledgeops-agent-tempo-lite
)

compose() {
  docker compose --env-file "$DEMO_ENV_FILE" "$@"
}

log() {
  printf '[knowledgeops-demo] %s\n' "$*"
}

fail() {
  printf '[knowledgeops-demo] ERROR: %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage:
  ./scripts/demo.sh [up|verify|down|logs|restart]

Commands:
  up       Create .env.demo when missing, build/start the stack, wait for health, run smoke checks.
  verify   Re-run health and smoke checks against an already running stack.
  down     Stop the demo stack.
  logs     Show recent app and web logs.
  restart  Stop, then run up.

Useful environment variables:
  DEMO_ENV_FILE=.env.demo        Env file used by docker compose interpolation.
  DEMO_RESET=1                  Remove volumes before starting.
  DEMO_REPLACE_CONFLICTS=1      Remove running legacy containers with fixed demo names.
  DEMO_SKIP_BUILD=1             Start existing images without rebuilding.
  DEMO_SKIP_E2E=1               Skip the Python chat smoke test.
  HEALTH_TIMEOUT_SECONDS=300    Max wait time for API/web readiness.
USAGE
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required but was not found"
}

preflight() {
  require_command docker
  require_command curl
  require_command python3

  docker compose version >/dev/null 2>&1 || fail "docker compose is required"
  docker info >/dev/null 2>&1 || fail "Docker is not running"
}

ensure_demo_env() {
  if [[ -f "$DEMO_ENV_FILE" ]]; then
    log "using existing $DEMO_ENV_FILE"
    return
  fi

  log "creating $DEMO_ENV_FILE"
  cat > "$DEMO_ENV_FILE" <<'ENV'
# Generated by scripts/demo.sh.
# This file is intentionally gitignored.
#
# Optional: set OPENAI_API_KEY and OPENAI_BASE_URL here to use a real
# OpenAI-compatible model provider. When omitted, docker-compose.yml uses
# its local placeholder defaults for smoke/demo flows.
#
# OPENAI_API_KEY=
# OPENAI_BASE_URL=
ENV
}

cleanup_conflicting_containers() {
  compose down --remove-orphans >/dev/null 2>&1 || true

  local name id status project
  for name in "${DEMO_CONTAINERS[@]}"; do
    id="$(docker ps -aq --filter "name=^/${name}$" | head -n 1)"
    [[ -n "$id" ]] || continue

    project="$(docker inspect -f '{{ index .Config.Labels "com.docker.compose.project" }}' "$id" 2>/dev/null || true)"
    [[ "$project" != "$COMPOSE_PROJECT_NAME" ]] || continue

    status="$(docker inspect -f '{{ .State.Status }}' "$id" 2>/dev/null || true)"
    if [[ "$status" == "running" && "${DEMO_REPLACE_CONFLICTS:-0}" != "1" ]]; then
      fail "container $name is already running from compose project '$project'. Stop it first or rerun with DEMO_REPLACE_CONFLICTS=1"
    fi

    log "removing stale container $name from compose project '${project:-unknown}'"
    docker rm -f "$id" >/dev/null
  done
}

wait_for_url() {
  local label="$1"
  local url="$2"
  local expected_code="${3:-200}"
  local elapsed=0

  log "waiting for $label at $url"
  while (( elapsed < HEALTH_TIMEOUT_SECONDS )); do
    local code
    code="$(curl -s -o /dev/null -w '%{http_code}' "$url" || true)"
    if [[ "$code" == "$expected_code" ]]; then
      log "$label is ready"
      return
    fi
    sleep "$HEALTH_POLL_SECONDS"
    elapsed=$((elapsed + HEALTH_POLL_SECONDS))
  done

  compose ps || true
  fail "$label did not become ready within ${HEALTH_TIMEOUT_SECONDS}s"
}

run_e2e() {
  if [[ "${DEMO_SKIP_E2E:-0}" == "1" ]]; then
    log "skipping e2e chat smoke test because DEMO_SKIP_E2E=1"
    return
  fi

  log "running e2e chat smoke test"
  python3 scripts/e2e_chat_flow.py --base-url "$API_BASE_URL"
}

verify_stack() {
  wait_for_url "API health" "$API_BASE_URL/actuator/health" "200"
  wait_for_url "web console" "$WEB_URL/" "200"
  run_e2e
  print_success
}

print_success() {
  cat <<EOF

KnowledgeOps Agent demo is ready.

Frontend console: $WEB_URL
Backend API:      $API_BASE_URL
Swagger UI:       $API_BASE_URL/swagger-ui/index.html
Health:           $API_BASE_URL/actuator/health
Metrics:          $API_BASE_URL/actuator/prometheus
RabbitMQ:         $RABBITMQ_URL

Useful commands:
  ./scripts/demo.sh verify
  ./scripts/demo.sh logs
  ./scripts/demo.sh down
EOF
}

start_stack() {
  preflight
  ensure_demo_env

  if [[ "${DEMO_RESET:-0}" == "1" ]]; then
    log "DEMO_RESET=1, removing existing demo containers and volumes"
    compose down -v --remove-orphans
  fi
  cleanup_conflicting_containers

  if [[ "${DEMO_SKIP_BUILD:-0}" == "1" ]]; then
    log "starting Docker Compose stack without rebuilding because DEMO_SKIP_BUILD=1"
    compose up -d
  else
    log "building and starting Docker Compose stack"
    compose up --build -d
  fi
  verify_stack
}

stop_stack() {
  preflight
  ensure_demo_env
  compose down --remove-orphans
}

show_logs() {
  preflight
  ensure_demo_env
  compose logs --tail=200 app web
}

case "$COMMAND" in
  up)
    start_stack
    ;;
  verify)
    preflight
    ensure_demo_env
    verify_stack
    ;;
  down)
    stop_stack
    ;;
  logs)
    show_logs
    ;;
  restart)
    stop_stack
    start_stack
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage
    fail "unknown command: $COMMAND"
    ;;
esac
